apiVersion: v1
kind: Namespace
metadata:
  name: slackbot
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-slackbot
  name: kube-slackbot
  namespace: slackbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-slackbot
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: kube-slackbot
    spec:
      containers:
        - env:
            - name: SLACKBOT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slackbot-secrets
                  key: SLACKBOT_API_TOKEN
            - name: ECR_REGISTRY
              value: "<YOUR ECR REGISTER:  for example: 913213535560.dkr.ecr.us-east-2.amazonaws.com>"
            - name: DEPLOYBOT_USER_ID
              value: "<YOUR BOT USER ID FROM PREVIOUS STEPS>"
            - name: AWS_ACCOUNT_ID
              value: "<YOUR AWS ACCOUNT ID>"
            - name: AWS_DEFAULT_REGION
              value: "<YOUR AWS REGION>"
            - name: AWS_ACCESS_KEY_ID
              value: "<YOUR AWS ACCESS KEY>"
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: slackbot-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: KUBE_CLUSTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slackbot-secrets
                  key: KUBE_TOKEN
            - name: KUBE_CLUSTER_ENDPOINT
              value: "<YOUR SECOND KUBERENTES TOKEN, IF YOU NEED IT>"
            - name: KUBE_CLUSTER_TOKEN2
              valueFrom:
                secretKeyRef:
                  name: slackbot-secrets
                  key: KUBE_TOKEN
            - name: KUBE_CLUSTER_ENDPOINT2
              value: "<YOUR SECOND KUBERENTES TOKEN, IF YOU NEED IT>"
          imagePullPolicy: Always
          image: <YOUR ECR REGISTER>>/slackbot:latest
          name: slackbot


